### ISSUE TITLE
Create Multi-Modal Login Page

### ISSUE THREAD

**Issue by oliverspryn** [oliverspryn/branham-player-android#25]
As a user, I need support for both my phone and tablet so that I can be most effective on both devices.

**Acceptance Criteria:**
- GIVEN a device with a screen size of less than `600dp`
  - WHEN viewing the login screen
    - [x] THEN the background of the screen is `#FFFFFF`
    - [x] THEN there is no toolbar
    - [x] THEN the status bar has a color of `#3086D4`
    - [x] THEN a generic, square logo placeholder displays at the top of the screen
    - [x] THEN below the logo is the word "Branham Player" in large text
    - [x] THEN below the app name is the phrase "A flexible audio player for all of your Android devices"
    - [x] THEN near the bottom of the screen is a Login button
    - [x] AND the Login button has a background with a linear gradient from `#3086D4` to `#5AFDFF` from the top-left to the bottom right
    - [x] AND clicking the Login button goes to the login screen
    - [x] THEN below the Login button is the text "New to Branham Player? Register"
    - [x] AND the word Register uses the accent color of `#5AFDFF`
    - [x] AND clicking the Register links goes to the registration screen
- GIVEN a device with a screen size of more than `600dp`
  - WHEN viewing the login screen
    - [x] THEN the background of the screen is `#EEEEEE`
    - [x] THEN the entire screen is scrollable
    - [x] THEN there is a toolbar
    - [x] AND the toolbar has no title
    - [x] AND the toolbar has a primary color of `#3DA7F8`
    - [x] AND the toolbar is `240dp` tall
    - [x] THEN the status bar has a color of `#3086D4`
    - [x] THEN the content of the page is placed within a card view
    - [x] AND the card view has a background color of `#FFFFFF`
    - [x] AND the card view is `540dp` wide
    - [x] AND the card view is `480dp` tall
    - [x] AND the card view is `60dp` from the top of the screen
    - [x] THEN a generic, square logo placeholder displays at the top of the card view
    - [x] THEN below the logo is the word "Branham Player" in large text
    - [x] THEN below the app name is the phrase "A flexible audio player for all of your Android devices"
    - [x] THEN near the bottom of the card view is a Login button
    - [x] AND the Login button has a background with a linear gradient from `#3086D4` to `#5AFDFF` from the top-left to the bottom right
    - [x] AND clicking the Login button goes to the login screen
    - [x] THEN below the Login button is the text "New to Branham Player? Register"
    - [x] AND the word Register uses the accent color of `#5AFDFF`
    - [x] AND clicking the Register links goes to the registration screen
- GIVEN a device with a screen size of more than `840dp`
  - WHEN viewing the login screen
    - [x] THEN everything is the same as the `600dp` screen, except the card view is `120dp` from the top of the screen
    
**Dev Note:** Look at these screens for inspiration

- https://cdn-images-1.medium.com/max/1600/0*jOuWfTo67EVhc_JP.
- https://i2.wp.com/www.vuescript.com/wp-content/uploads/2017/08/Material-Design-for-Vue.js-2.png?w=1600&ssl=1
- https://cdn-images-1.medium.com/max/1600/0*R2rPoDTWbeNAgQXi.
